# Generated by Django 2.0.7 on 2020-01-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 's'},
        ),
    ]
